const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.NoSave,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.sliderbar,
		C3.Plugins.Keyboard,
		C3.Plugins.List,
		C3.Behaviors.bound,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Text.Acts.SetZElevation,
		C3.Plugins.Text.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Button.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.sliderbar.Acts.SetVisible,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Button.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Button.Acts.MoveAtAngle,
		C3.Plugins.TiledBg.Acts.MoveAtAngle,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Button.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Cnds.CompareZElevation,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsNaN,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Girar: 0},
	{Interpolação: 0},
	{fan: 0},
	{Senóide: 0},
	{fanparts: 0},
	{Mouse: 0},
	{SpeedText: 0},
	{shadow: 0},
	{Esmaecer: 0},
	{NãoSalvar: 0},
	{plusmoneytext: 0},
	{scroll: 0},
	{tomada: 0},
	{hamster: 0},
	{factory: 0},
	{panel: 0},
	{saltwater: 0},
	{backgrounds: 0},
	{level: 0},
	{auto_cursor: 0},
	{value: 0},
	{product: 0},
	{product_name: 0},
	{question: 0},
	{ativo: 0},
	{genericBuyButton: 0},
	{saveandloadtext: 0},
	{savetextmark: 0},
	{menu_sprite: 0},
	{oldantilagwarning: 0},
	{liteModeButton: 0},
	{Touch: 0},
	{crashWarning: 0},
	{resetvalues: 0},
	{click_cur: 0},
	{cursorpreview: 0},
	{cur: 0},
	{to: 0},
	{button_to: 0},
	{shopbg: 0},
	{wood: 0},
	{cursorsprite: 0},
	{carpetbg1: 0},
	{bed: 0},
	{icon: 0},
	{none: 0},
	{ventuinha: 0},
	{buyButtonUiText: 0},
	{AudioPlayer: 0},
	{outlet: 0},
	{name: 0},
	{mini_fan: 0},
	{click_effect: 0},
	{talk: 0},
	{police: 0},
	{version_text: 0},
	{mini_cur: 0},
	{buy_text: 0},
	{scrollarea: 0},
	{scrollarea2: 0},
	{keyboardToScrollWarning: 0},
	{moinho: 0},
	{rgb_light: 0},
	{rgb_speed_bar: 0},
	{icon2: 0},
	{carpetbg2: 0},
	{end: 0},
	{wintexts: 0},
	{star: 0},
	{space_shadow: 0},
	{Keyboard: 0},
	{genericbutton: 0},
	{PowerText: 0},
	{hamsterdialogbottom: 0},
	{HamsterNameTextUi: 0},
	{hamsterdialog: 0},
	{HamsterNamesList: 0},
	{Senóide2: 0},
	{RestritoAoLayout: 0},
	{specialbattery: 0},
	{buttonstype1: 0},
	{speed: 0},
	{cursorLevel: 0},
	{cursorLevel2: 0},
	{click_value: 0},
	{coisa: 0},
	{doubleCursor: 0},
	{cursor: 0},
	{CUR2: 0},
	{tomadas: 0},
	{cur_period: 0},
	{curangle: 0},
	{hamsterspeed: 0},
	{hamsterspeed2: 0},
	{rebirths: 0},
	{hamsters_current_skinslimit: 0},
	{totalhamstersvariants: 0}
];

self.InstanceType = {
	fan: class extends self.ISpriteInstance {},
	fanparts: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	SpeedText: class extends self.ITextInstance {},
	plusmoneytext: class extends self.ITextInstance {},
	backgrounds: class extends self.ISpriteInstance {},
	auto_cursor: class extends self.ISpriteInstance {},
	genericBuyButton: class extends self.IButtonInstance {},
	saveandloadtext: class extends self.ITextInstance {},
	savetextmark: class extends self.ISpriteInstance {},
	menu_sprite: class extends self.ITiledBackgroundInstance {},
	oldantilagwarning: class extends self.ITextInstance {},
	liteModeButton: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {},
	crashWarning: class extends self.ITextInstance {},
	resetvalues: class extends self.IButtonInstance {},
	click_cur: class extends self.ISpriteInstance {},
	cursorpreview: class extends self.ISpriteInstance {},
	cur: class extends self.ISpriteInstance {},
	button_to: class extends self.ISpriteInstance {},
	shopbg: class extends self.ISpriteInstance {},
	wood: class extends self.ITiledBackgroundInstance {},
	cursorsprite: class extends self.ISpriteInstance {},
	carpetbg1: class extends self.ITiledBackgroundInstance {},
	bed: class extends self.ISpriteInstance {},
	icon: class extends self.ISpriteInstance {},
	none: class extends self.ISpriteInstance {},
	ventuinha: class extends self.ITiledBackgroundInstance {},
	buyButtonUiText: class extends self.ITextInstance {},
	AudioPlayer: class extends self.IInstance {},
	outlet: class extends self.ISpriteInstance {},
	hamster: class extends self.ISpriteInstance {},
	mini_fan: class extends self.ITiledBackgroundInstance {},
	click_effect: class extends self.IParticlesInstance {},
	police: class extends self.ISpriteInstance {},
	version_text: class extends self.ITextInstance {},
	mini_cur: class extends self.ISpriteInstance {},
	buy_text: class extends self.ITextInstance {},
	scrollarea: class extends self.ISpriteInstance {},
	scrollarea2: class extends self.ISpriteInstance {},
	panel: class extends self.ISpriteInstance {},
	keyboardToScrollWarning: class extends self.ITextInstance {},
	moinho: class extends self.ISpriteInstance {},
	rgb_light: class extends self.ITiledBackgroundInstance {},
	rgb_speed_bar: class extends self.ISliderBarInstance {},
	icon2: class extends self.ISpriteInstance {},
	carpetbg2: class extends self.ITiledBackgroundInstance {},
	wintexts: class extends self.ITextInstance {},
	star: class extends self.ISpriteInstance {},
	space_shadow: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	genericbutton: class extends self.IButtonInstance {},
	PowerText: class extends self.ITextInstance {},
	hamsterdialogbottom: class extends self.ISpriteInstance {},
	HamsterNameTextUi: class extends self.ITextInstance {},
	hamsterdialog: class extends self.ISpriteInstance {},
	HamsterNamesList: class extends self.IListInstance {},
	specialbattery: class extends self.ISpriteInstance {},
	buttonstype1: class extends self.IButtonInstance {}
}