const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{static_bg: 0},
	{Logo: 0},
	{GoTo: 0},
	{goBack: 0},
	{Mouse: 0},
	{mouseHighlight: 0},
	{Texto: 0},
	{add: 0},
	{player_select_a: 0},
	{Plataforma: 0},
	{player1: 0},
	{player2: 0},
	{player_select_b: 0},
	{Sólido: 0},
	{Solid: 0},
	{background: 0},
	{Teclado: 0},
	{preview_player1: 0},
	{preview_player2: 0},
	{health_bar_p1: 0},
	{player1_name: 0},
	{health_bar_p2: 0},
	{dir: 0},
	{attack_p1: 0},
	{attack_p2: 0},
	{stamina_bar_p1: 0},
	{stamina_bar_p2: 0},
	{Matriz: 0},
	{AJAX: 0},
	{player2_name: 0},
	{Wins: 0},
	{Count: 0},
	{Audio: 0},
	{damageCountText: 0},
	{player1_wins: 0},
	{player2_wins: 0},
	{player1_id: 0},
	{player2_id: 0},
	{player1_health: 0},
	{player1_maxhealth: 0},
	{player2_health: 0},
	{player2_maxhealth: 0},
	{player1_stamina: 0},
	{player1_dashpower: 0},
	{player2_dashpower: 0},
	{player1_maxstamina: 0},
	{player2_stamina: 0},
	{player2_maxstamina: 0},
	{player2_damage: 0},
	{player1_damage: 0},
	{charData: 0}
];

self.InstanceType = {
	static_bg: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	goBack: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	mouseHighlight: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	player_select_a: class extends self.ISpriteInstance {},
	player1: class extends self.ISpriteInstance {},
	player2: class extends self.ISpriteInstance {},
	player_select_b: class extends self.ISpriteInstance {},
	Solid: class extends self.ITiledBackgroundInstance {},
	background: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	preview_player1: class extends self.ISpriteInstance {},
	preview_player2: class extends self.ISpriteInstance {},
	health_bar_p1: class extends self.ITiledBackgroundInstance {},
	player1_name: class extends self.ITextInstance {},
	health_bar_p2: class extends self.ITiledBackgroundInstance {},
	attack_p1: class extends self.ISpriteInstance {},
	attack_p2: class extends self.ISpriteInstance {},
	stamina_bar_p1: class extends self.ITiledBackgroundInstance {},
	stamina_bar_p2: class extends self.ITiledBackgroundInstance {},
	Matriz: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	player2_name: class extends self.ITextInstance {},
	Wins: class extends self.ITextInstance {},
	Count: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	damageCountText: class extends self.ITextInstance {}
}