const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.NoSave,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Flash,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.gamepad,
		C3.Behaviors.Follow,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Spritefont2.Acts.SetWrapping,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Acts.SetLayerBlendMode,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{Mouse: 0},
	{Sólido: 0},
	{Física: 0},
	{NãoSalvar: 0},
	{tiles: 0},
	{player: 0},
	{frogtype: 0},
	{currentjump: 0},
	{Plataforma: 0},
	{PularAtravés: 0},
	{player_hitbox: 0},
	{other: 0},
	{Piscar: 0},
	{player_sprites: 0},
	{Girar: 0},
	{blades: 0},
	{genericsprite: 0},
	{sin: 0},
	{coin: 0},
	{physic_tile: 0},
	{Senóide: 0},
	{font1: 0},
	{DestruirForaDoLayout: 0},
	{Esmaecer: 0},
	{blackk: 0},
	{CentrarEm: 0},
	{cam: 0},
	{blackk2: 0},
	{spikes: 0},
	{dying_particles: 0},
	{lava: 0},
	{falling: 0},
	{starterY: 0},
	{wait: 0},
	{speed: 0},
	{delay: 0},
	{heavy: 0},
	{fall_on_touch: 0},
	{fall_block: 0},
	{trigger: 0},
	{Reason: 0},
	{hitkill: 0},
	{sine: 0},
	{UID_orange: 0},
	{portal1: 0},
	{uid_blue: 0},
	{portal2: 0},
	{range: 0},
	{vertical_fan: 0},
	{bevisible: 0},
	{last: 0},
	{flag: 0},
	{Audio: 0},
	{particlee: 0},
	{arrow: 0},
	{arrow2: 0},
	{arrow3: 0},
	{Toque: 0},
	{InformaçãoDaPlataforma: 0},
	{CoinCounter: 0},
	{Gamepad: 0},
	{font2: 0},
	{security_camera: 0},
	{bg: 0},
	{value: 0},
	{options: 0},
	{screen_bound1: 0},
	{screen_bound2: 0},
	{P_indicator: 0},
	{p: 0},
	{value_num: 0},
	{haticon: 0},
	{checkp1: 0},
	{checkp2: 0},
	{horizontal_fan: 0},
	{view: 0},
	{Seguir: 0},
	{ghost: 0},
	{generic2: 0},
	{froghat: 0},
	{Âncora: 0},
	{anchorgeneric: 0},
	{checkhatp1: 0},
	{checkhatp2: 0},
	{bgoptions: 0},
	{checkhatp3: 0},
	{gunrange: 0},
	{rotatingspeed: 0},
	{mini_cannon: 0},
	{Projétil: 0},
	{bullet: 0},
	{portal_particles: 0},
	{bullet_break: 0},
	{star_particle: 0},
	{bg2: 0},
	{tinyFont: 0},
	{track: 0},
	{players: 0},
	{minn: 0},
	{sec: 0},
	{Coins: 0},
	{controltype: 0},
	{p1color: 0},
	{checkpointX: 0},
	{checkpointY: 0},
	{p2color: 0},
	{p1hat: 0},
	{p2hat: 0},
	{paused: 0},
	{maxjumpheight: 0},
	{minjumpheight: 0},
	{addtojump: 0},
	{deathcounter: 0},
	{lastlevel: 0},
	{LIBERADO: 0},
	{health: 0},
	{Minutes: 0},
	{Seconds: 0},
	{Miliseconds: 0},
	{DeathReason: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	tiles: class extends self.ITilemapInstance {},
	player_hitbox: class extends self.ISpriteInstance {},
	player_sprites: class extends self.ISpriteInstance {},
	blades: class extends self.ISpriteInstance {},
	genericsprite: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	physic_tile: class extends self.ISpriteInstance {},
	font1: class extends self.ISpriteFontInstance {},
	blackk: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	blackk2: class extends self.ISpriteInstance {},
	spikes: class extends self.ISpriteInstance {},
	dying_particles: class extends self.IParticlesInstance {},
	lava: class extends self.ITiledBackgroundInstance {},
	fall_block: class extends self.ISpriteInstance {},
	trigger: class extends self.ISpriteInstance {},
	hitkill: class extends self.ISpriteInstance {},
	sine: class extends self.ISpriteInstance {},
	portal1: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	vertical_fan: class extends self.ISpriteInstance {},
	bevisible: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	particlee: class extends self.IParticlesInstance {},
	arrow: class extends self.ISpriteInstance {},
	arrow2: class extends self.ISpriteInstance {},
	arrow3: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	InformaçãoDaPlataforma: class extends self.IInstance {},
	CoinCounter: class extends self.ISpriteFontInstance {},
	Gamepad: class extends self.IInstance {},
	font2: class extends self.ISpriteFontInstance {},
	security_camera: class extends self.ISpriteInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	options: class extends self.ISpriteFontInstance {},
	screen_bound1: class extends self.ITiledBackgroundInstance {},
	screen_bound2: class extends self.ITiledBackgroundInstance {},
	P_indicator: class extends self.ISpriteFontInstance {},
	haticon: class extends self.ISpriteInstance {},
	checkp1: class extends self.ISpriteInstance {},
	checkp2: class extends self.ISpriteInstance {},
	horizontal_fan: class extends self.ISpriteInstance {},
	view: class extends self.ISpriteInstance {},
	ghost: class extends self.ISpriteInstance {},
	generic2: class extends self.ISpriteFontInstance {},
	froghat: class extends self.ISpriteInstance {},
	anchorgeneric: class extends self.ISpriteInstance {},
	checkhatp1: class extends self.ISpriteInstance {},
	checkhatp2: class extends self.ISpriteInstance {},
	bgoptions: class extends self.ISpriteInstance {},
	checkhatp3: class extends self.ISpriteInstance {},
	mini_cannon: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	portal_particles: class extends self.IParticlesInstance {},
	bullet_break: class extends self.IParticlesInstance {},
	star_particle: class extends self.IParticlesInstance {},
	bg2: class extends self.ITiledBackgroundInstance {},
	tinyFont: class extends self.ISpriteFontInstance {},
	track: class extends self.ISpriteInstance {},
	players: class extends self.ISpriteInstance {}
}